#!/bin/bash
# ROI Quick Reference - Idle People Violation

echo "============================================================"
echo "  ROI Setup - Idle People Violation"
echo "  Quick Reference Guide"
echo "============================================================"
echo ""
echo "📍 Current Status:"
echo "   - Channel ID: cam_bc9c1f31"
echo "   - App Name: IdlePeopleViolation"
echo "   - Camera Name: Front Office"
echo ""
echo "🌐 Web URLs:"
echo "   1. ROI Editor:    http://localhost:5003/roi_editor_idle_people"
echo "   2. Live Monitor:  http://localhost:5003/idle-people-violation"
echo "   3. Dashboard:     http://localhost:5003/dashboard"
echo ""
echo "🔧 Commands:"
echo "   Test ROI:         python scripts/test_roi_idle_people.py"
echo "   Check Database:   psql -U postgres -d sakshi -c \"SELECT * FROM roi_configs WHERE app_name='IdlePeopleViolation';\""
echo ""
echo "📋 How to Set Up ROI:"
echo "   1. Visit: http://localhost:5003/roi_editor_idle_people"
echo "   2. Click on video frame to add points (minimum 3)"
echo "   3. Yellow polygon shows your monitoring zone"
echo "   4. Click 'Save ROI' when done"
echo "   5. Restart app or wait for auto-reload"
echo "   6. Verify yellow overlay on live feed"
echo ""
echo "🎨 Visual Indicators:"
echo "   - Yellow polygon:  ROI monitoring zone"
echo "   - Green box:       Person tracked, not idle"
echo "   - Red box:         IDLE violation (15+ frames)"
echo ""
echo "📁 Documentation:"
echo "   - Detailed Guide:  docs/ROI_SETUP_IDLE_PEOPLE.md"
echo "   - Summary:         docs/ROI_SETUP_COMPLETE.md"
echo "   - Implementation:  DB/IDLE_PEOPLE_VIOLATION_IMPLEMENTATION.md"
echo ""
echo "✅ Quick Test:"
echo "   Running ROI test script..."
echo ""
python scripts/test_roi_idle_people.py
echo ""
echo "============================================================"
echo "  For help, see: docs/ROI_SETUP_IDLE_PEOPLE.md"
echo "============================================================"
